# Drop Folder Configuration
# Configuration for automated test generation from requirement files

drop_folder:
  # Base path for drop folder system (relative to project root)
  base_path: "./drop_folder"
  
  # Subdirectories
  input_dir: "input"
  output_dir: "output"
  archive_dir: "archive"
  processing_dir: "processing"
  errors_dir: "errors"
  
  # File monitoring settings
  watch_interval: 5  # seconds between directory scans
  file_extensions: [".txt", ".md", ".text"]  # Accepted file types
  debounce_delay: 2  # seconds to wait after last file modification
  max_file_size_mb: 10  # Maximum file size in MB
  
  # Processing settings
  use_rag: true  # Enable RAG-enhanced generation
  top_k_similar: 5  # Number of similar tests to retrieve
  min_similarity: 0.5  # Minimum similarity threshold for RAG
  
  # Model configuration
  model_checkpoint: "fine_tuned_checkpoints/media_fulfillment/checkpoint_epoch_3_best.pt"
  fallback_checkpoint: "checkpoints_hrm_v9_optimized_step_7566"  # Fallback if fine-tuned not available
  use_fine_tuned: true  # Prefer fine-tuned model if available
  
  # Output format settings
  save_json: true  # Save test cases as JSON
  save_markdown: true  # Save test cases as Markdown
  generate_report: true  # Generate processing report
  include_metadata: true  # Include RAG and processing metadata
  
  # Security settings
  rate_limit_per_minute: 10  # Max files to process per minute
  validate_file_content: true  # Check for suspicious content
  
  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "drop_folder/drop_folder.log"
